---
# node 1
spring:
  application:
    name: points
  profiles: points_node1
server:
  port: 13001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
---
# node 2
spring:
  application:
    name: points
  profiles: points_node2
server:
  port: 13002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
