---
# node 1
spring:
  application:
    name: spring-cloud-eureka
  profiles: node1
server:
  port: 10001
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/,http://localhost:10003/eureka/
---
# node 2
spring:
  application:
    name: spring-cloud-eureka
  profiles: node2
server:
  port: 10002
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10003/eureka/
---
# node 3
spring:
  application:
    name: spring-cloud-eureka
  profiles: node3
server:
  port: 10003
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
