---
# node 1
spring:
  application:
    name: order
  profiles: order_node1
server:
  port: 12001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
feign:
  hystrix:
    enabled: true      

---
# node 2
spring:
  application:
    name: order
  profiles: order_node2
server:
  port: 12002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
feign:
  hystrix:
    enabled: true   
