---
# node 1
spring:
  application:
    name: producer1
  profiles: node1
server:
  port: 11001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
---
# node 2
spring:
  application:
    name: producer1
  profiles: node2
server:
  port: 11002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
