---
# node 1
spring:
  application:
    name: commodity
  profiles: commodity_node1
server:
  port: 21001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
---
# node 2
spring:
  application:
    name: commodity
  profiles: commodity_node2
server:
  port: 21002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
